# Generated by Django 4.0.4 on 2022-06-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empolyee', '0003_remove_empolyeeeducation_company1desig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empolyeeeducation',
            old_name='yearofpassingshc',
            new_name='yearofpassinghsc',
        ),
    ]
